FROM node:16-alpine AS build
WORKDIR /app

# Tận dụng cơ chế caching, nếu config không có thay đổi sẽ không install thư viện
COPY package*.json ./                   
RUN npm install

COPY . .
RUN npm run build

# Serve Application using Nginx Server
FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY ssl-localhost /etc/nginx/ssl-localhost

# COPY --from=build /app/dist/angular-frontend/ /usr/share/nginx/html
COPY /dist/angular-frontend/ /usr/share/nginx/html

EXPOSE 80
EXPOSE 443

# .dockerignore : Sẽ bỏ qua các mục nằm trong file này : Bỏ build, node_modules